# Generated by Django 4.0.4 on 2022-05-03 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_Account', '0002_customuser_masteru_admin_staff_admin_students_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masteru',
            name='email',
        ),
        migrations.RemoveField(
            model_name='masteru',
            name='name',
        ),
        migrations.RemoveField(
            model_name='masteru',
            name='password',
        ),
        migrations.DeleteModel(
            name='Note_Staff',
        ),
    ]
