# Generated by Django 4.0.4 on 2022-05-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_Account', '0003_remove_masteru_email_remove_masteru_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
