# Generated by Django 4.0.4 on 2022-05-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_Account', '0005_attendance_student_attendance_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_student',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='attendance_teacher',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
