# Generated by Django 4.0.4 on 2022-05-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_Account', '0006_alter_attendance_student_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
