# Generated by Django 4.0.4 on 2022-05-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_Account', '0007_mark_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_student',
            name='attendance_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attendance_teacher',
            name='attendance_date',
            field=models.DateTimeField(),
        ),
    ]
