# Generated by Django 4.0.4 on 2022-05-06 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portal_Account', '0008_alter_attendance_student_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note_student',
            name='staff_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Portal_Account.staff'),
        ),
    ]
